# Generated by Django 3.2.16 on 2022-10-26 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscernType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=32, unique=True, verbose_name='识别类别名称')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('gender', models.SmallIntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='性别')),
                ('phone', models.CharField(default='', max_length=11, verbose_name='电话号码')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='邮箱')),
                ('headPortrait', models.CharField(default='', max_length=128, verbose_name='头像')),
                ('sq', models.CharField(default='', max_length=32, verbose_name='密保')),
                ('sqKey', models.CharField(default='', max_length=32, verbose_name='密保密码')),
                ('info', models.CharField(default='', max_length=32, verbose_name='个人简介')),
            ],
        ),
        migrations.CreateModel(
            name='DiscernModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='', max_length=32, verbose_name='具体模型名称')),
                ('name', models.CharField(max_length=32, verbose_name='模型内部名称')),
                ('discernType', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api1.discerntype')),
            ],
        ),
    ]
