# Generated by Django 3.2.16 on 2022-10-27 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=256, verbose_name='识别完毕的图像')),
                ('date', models.DateField(verbose_name='识别时间')),
                ('result', models.CharField(max_length=256, verbose_name='识别结果')),
                ('discernModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api1.discernmodel', verbose_name='使用的模型')),
                ('discernType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api1.discerntype', verbose_name='识别类型')),
            ],
        ),
    ]
