# Generated by Django 3.2.16 on 2022-10-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0003_record_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=32, verbose_name='识别出的物体标签')),
                ('info', models.TextField(verbose_name='详细描述')),
            ],
        ),
    ]
