# Generated by Django 3.2.16 on 2022-10-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0004_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='delete',
            field=models.BooleanField(default=False, verbose_name='逻辑删除'),
        ),
    ]
