# Generated by Django 3.2.16 on 2022-10-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0005_user_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discernmodel',
            name='label',
            field=models.CharField(default='', max_length=32, unique=True, verbose_name='具体模型名称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='delete',
            field=models.BooleanField(default=False, verbose_name='禁用'),
        ),
    ]
